import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { redirect } from "next/navigation";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});
// Font files can be colocated inside of `app`
// const myFont = localFont({
//   src: "./fonts/AROneSans-VariableFont_ARRR,wght.ttf",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <div className="RootLayout">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
